export type WordCategory = 'animals' | 'food' | 'actions' | 'objects';

export interface Word {
  id: string;
  text: string;
  category: WordCategory;
}

export const WORD_BANK: Word[] = [
  // ANIMALS (45 words)
  { id: 'a1', text: 'Dog', category: 'animals' },
  { id: 'a2', text: 'Cat', category: 'animals' },
  { id: 'a3', text: 'Elephant', category: 'animals' },
  { id: 'a4', text: 'Monkey', category: 'animals' },
  { id: 'a5', text: 'Rabbit', category: 'animals' },
  { id: 'a6', text: 'Lion', category: 'animals' },
  { id: 'a7', text: 'Snake', category: 'animals' },
  { id: 'a8', text: 'Fish', category: 'animals' },
  { id: 'a9', text: 'Bird', category: 'animals' },
  { id: 'a10', text: 'Horse', category: 'animals' },
  { id: 'a11', text: 'Cow', category: 'animals' },
  { id: 'a12', text: 'Pig', category: 'animals' },
  { id: 'a13', text: 'Chicken', category: 'animals' },
  { id: 'a14', text: 'Duck', category: 'animals' },
  { id: 'a15', text: 'Frog', category: 'animals' },
  { id: 'a16', text: 'Turtle', category: 'animals' },
  { id: 'a17', text: 'Bear', category: 'animals' },
  { id: 'a18', text: 'Tiger', category: 'animals' },
  { id: 'a19', text: 'Giraffe', category: 'animals' },
  { id: 'a20', text: 'Kangaroo', category: 'animals' },
  { id: 'a21', text: 'Penguin', category: 'animals' },
  { id: 'a22', text: 'Dolphin', category: 'animals' },
  { id: 'a23', text: 'Shark', category: 'animals' },
  { id: 'a24', text: 'Butterfly', category: 'animals' },
  { id: 'a25', text: 'Spider', category: 'animals' },
  { id: 'a26', text: 'Bee', category: 'animals' },
  { id: 'a27', text: 'Owl', category: 'animals' },
  { id: 'a28', text: 'Eagle', category: 'animals' },
  { id: 'a29', text: 'Parrot', category: 'animals' },
  { id: 'a30', text: 'Zebra', category: 'animals' },
  { id: 'a31', text: 'Hippo', category: 'animals' },
  { id: 'a32', text: 'Crocodile', category: 'animals' },
  { id: 'a33', text: 'Mouse', category: 'animals' },
  { id: 'a34', text: 'Hamster', category: 'animals' },
  { id: 'a35', text: 'Squirrel', category: 'animals' },
  { id: 'a36', text: 'Deer', category: 'animals' },
  { id: 'a37', text: 'Fox', category: 'animals' },
  { id: 'a38', text: 'Wolf', category: 'animals' },
  { id: 'a39', text: 'Gorilla', category: 'animals' },
  { id: 'a40', text: 'Peacock', category: 'animals' },
  { id: 'a41', text: 'Seal', category: 'animals' },
  { id: 'a42', text: 'Crab', category: 'animals' },
  { id: 'a43', text: 'Snail', category: 'animals' },
  { id: 'a44', text: 'Ant', category: 'animals' },
  { id: 'a45', text: 'Ladybug', category: 'animals' },

  // FOOD (45 words)
  { id: 'f1', text: 'Pizza', category: 'food' },
  { id: 'f2', text: 'Ice cream', category: 'food' },
  { id: 'f3', text: 'Banana', category: 'food' },
  { id: 'f4', text: 'Apple', category: 'food' },
  { id: 'f5', text: 'Watermelon', category: 'food' },
  { id: 'f6', text: 'Spaghetti', category: 'food' },
  { id: 'f7', text: 'Hamburger', category: 'food' },
  { id: 'f8', text: 'Hot dog', category: 'food' },
  { id: 'f9', text: 'Popcorn', category: 'food' },
  { id: 'f10', text: 'Cookie', category: 'food' },
  { id: 'f11', text: 'Cake', category: 'food' },
  { id: 'f12', text: 'Donut', category: 'food' },
  { id: 'f13', text: 'Sandwich', category: 'food' },
  { id: 'f14', text: 'Pancakes', category: 'food' },
  { id: 'f15', text: 'Cereal', category: 'food' },
  { id: 'f16', text: 'Orange', category: 'food' },
  { id: 'f17', text: 'Grapes', category: 'food' },
  { id: 'f18', text: 'Strawberry', category: 'food' },
  { id: 'f19', text: 'Carrot', category: 'food' },
  { id: 'f20', text: 'Broccoli', category: 'food' },
  { id: 'f21', text: 'French fries', category: 'food' },
  { id: 'f22', text: 'Chicken nuggets', category: 'food' },
  { id: 'f23', text: 'Taco', category: 'food' },
  { id: 'f24', text: 'Burrito', category: 'food' },
  { id: 'f25', text: 'Cheese', category: 'food' },
  { id: 'f26', text: 'Milk', category: 'food' },
  { id: 'f27', text: 'Juice', category: 'food' },
  { id: 'f28', text: 'Lemonade', category: 'food' },
  { id: 'f29', text: 'Cupcake', category: 'food' },
  { id: 'f30', text: 'Candy', category: 'food' },
  { id: 'f31', text: 'Chocolate', category: 'food' },
  { id: 'f32', text: 'Popsicle', category: 'food' },
  { id: 'f33', text: 'Corn on the cob', category: 'food' },
  { id: 'f34', text: 'Peanut butter', category: 'food' },
  { id: 'f35', text: 'Jelly', category: 'food' },
  { id: 'f36', text: 'Bread', category: 'food' },
  { id: 'f37', text: 'Eggs', category: 'food' },
  { id: 'f38', text: 'Bacon', category: 'food' },
  { id: 'f39', text: 'Soup', category: 'food' },
  { id: 'f40', text: 'Salad', category: 'food' },
  { id: 'f41', text: 'Muffin', category: 'food' },
  { id: 'f42', text: 'Pretzel', category: 'food' },
  { id: 'f43', text: 'Waffle', category: 'food' },
  { id: 'f44', text: 'Pineapple', category: 'food' },
  { id: 'f45', text: 'Lemon', category: 'food' },

  // ACTIONS (45 words)
  { id: 'ac1', text: 'Dancing', category: 'actions' },
  { id: 'ac2', text: 'Swimming', category: 'actions' },
  { id: 'ac3', text: 'Sleeping', category: 'actions' },
  { id: 'ac4', text: 'Running', category: 'actions' },
  { id: 'ac5', text: 'Jumping', category: 'actions' },
  { id: 'ac6', text: 'Eating', category: 'actions' },
  { id: 'ac7', text: 'Brushing teeth', category: 'actions' },
  { id: 'ac8', text: 'Taking a shower', category: 'actions' },
  { id: 'ac9', text: 'Reading a book', category: 'actions' },
  { id: 'ac10', text: 'Playing video games', category: 'actions' },
  { id: 'ac11', text: 'Riding a bike', category: 'actions' },
  { id: 'ac12', text: 'Climbing a tree', category: 'actions' },
  { id: 'ac13', text: 'Cooking', category: 'actions' },
  { id: 'ac14', text: 'Painting', category: 'actions' },
  { id: 'ac15', text: 'Singing', category: 'actions' },
  { id: 'ac16', text: 'Playing guitar', category: 'actions' },
  { id: 'ac17', text: 'Taking a photo', category: 'actions' },
  { id: 'ac18', text: 'Flying a kite', category: 'actions' },
  { id: 'ac19', text: 'Building a sandcastle', category: 'actions' },
  { id: 'ac20', text: 'Blowing bubbles', category: 'actions' },
  { id: 'ac21', text: 'Jumping rope', category: 'actions' },
  { id: 'ac22', text: 'Playing catch', category: 'actions' },
  { id: 'ac23', text: 'Hula hooping', category: 'actions' },
  { id: 'ac24', text: 'Skateboarding', category: 'actions' },
  { id: 'ac25', text: 'Roller skating', category: 'actions' },
  { id: 'ac26', text: 'Doing a cartwheel', category: 'actions' },
  { id: 'ac27', text: 'Yawning', category: 'actions' },
  { id: 'ac28', text: 'Sneezing', category: 'actions' },
  { id: 'ac29', text: 'Laughing', category: 'actions' },
  { id: 'ac30', text: 'Crying', category: 'actions' },
  { id: 'ac31', text: 'Waving hello', category: 'actions' },
  { id: 'ac32', text: 'Giving a high five', category: 'actions' },
  { id: 'ac33', text: 'Taking out trash', category: 'actions' },
  { id: 'ac34', text: 'Vacuuming', category: 'actions' },
  { id: 'ac35', text: 'Washing dishes', category: 'actions' },
  { id: 'ac36', text: 'Making the bed', category: 'actions' },
  { id: 'ac37', text: 'Watering plants', category: 'actions' },
  { id: 'ac38', text: 'Feeding a pet', category: 'actions' },
  { id: 'ac39', text: 'Walking a dog', category: 'actions' },
  { id: 'ac40', text: 'Opening a present', category: 'actions' },
  { id: 'ac41', text: 'Blowing out candles', category: 'actions' },
  { id: 'ac42', text: 'Typing on a computer', category: 'actions' },
  { id: 'ac43', text: 'Talking on the phone', category: 'actions' },
  { id: 'ac44', text: 'Putting on shoes', category: 'actions' },
  { id: 'ac45', text: 'Brushing hair', category: 'actions' },

  // OBJECTS (45 words)
  { id: 'o1', text: 'Airplane', category: 'objects' },
  { id: 'o2', text: 'Car', category: 'objects' },
  { id: 'o3', text: 'Bicycle', category: 'objects' },
  { id: 'o4', text: 'Ball', category: 'objects' },
  { id: 'o5', text: 'Book', category: 'objects' },
  { id: 'o6', text: 'Chair', category: 'objects' },
  { id: 'o7', text: 'Table', category: 'objects' },
  { id: 'o8', text: 'Phone', category: 'objects' },
  { id: 'o9', text: 'Television', category: 'objects' },
  { id: 'o10', text: 'Computer', category: 'objects' },
  { id: 'o11', text: 'Umbrella', category: 'objects' },
  { id: 'o12', text: 'Hat', category: 'objects' },
  { id: 'o13', text: 'Sunglasses', category: 'objects' },
  { id: 'o14', text: 'Toothbrush', category: 'objects' },
  { id: 'o15', text: 'Scissors', category: 'objects' },
  { id: 'o16', text: 'Camera', category: 'objects' },
  { id: 'o17', text: 'Guitar', category: 'objects' },
  { id: 'o18', text: 'Drum', category: 'objects' },
  { id: 'o19', text: 'Piano', category: 'objects' },
  { id: 'o20', text: 'Balloon', category: 'objects' },
  { id: 'o21', text: 'Kite', category: 'objects' },
  { id: 'o22', text: 'Teddy bear', category: 'objects' },
  { id: 'o23', text: 'Robot', category: 'objects' },
  { id: 'o24', text: 'Rocket ship', category: 'objects' },
  { id: 'o25', text: 'Train', category: 'objects' },
  { id: 'o26', text: 'Boat', category: 'objects' },
  { id: 'o27', text: 'Helicopter', category: 'objects' },
  { id: 'o28', text: 'Lamp', category: 'objects' },
  { id: 'o29', text: 'Clock', category: 'objects' },
  { id: 'o30', text: 'Mirror', category: 'objects' },
  { id: 'o31', text: 'Pillow', category: 'objects' },
  { id: 'o32', text: 'Blanket', category: 'objects' },
  { id: 'o33', text: 'Backpack', category: 'objects' },
  { id: 'o34', text: 'Lunchbox', category: 'objects' },
  { id: 'o35', text: 'Pencil', category: 'objects' },
  { id: 'o36', text: 'Crayons', category: 'objects' },
  { id: 'o37', text: 'Stickers', category: 'objects' },
  { id: 'o38', text: 'Skateboard', category: 'objects' },
  { id: 'o39', text: 'Trampoline', category: 'objects' },
  { id: 'o40', text: 'Swing', category: 'objects' },
  { id: 'o41', text: 'Slide', category: 'objects' },
  { id: 'o42', text: 'Trophy', category: 'objects' },
  { id: 'o43', text: 'Medal', category: 'objects' },
  { id: 'o44', text: 'Crown', category: 'objects' },
  { id: 'o45', text: 'Magic wand', category: 'objects' },
];
